melbourne_stations = {
    "Alamein": ["Alamein"],
    "Albion": ["Sunbury"],
    "Alphington": ["Hurstbridge"],
    "Altona": ["Werribee"],
    "Armadale": ["Frankston", "Pakenham", "Cranbourne"],
    "Ascot Vale": ["Craigieburn"],
    "Ashburton": ["Alamein"],
    "Batman": ["Upfield"],
    "Bayswater": ["Belgrave"],
    "Belgrave": ["Belgrave"],
    "Bentleigh": ["Frankston"],
    "Berwick": ["Pakenham"],
    "Blackburn": ["Belgrave", "Lilydale"],
    "Bonbeach": ["Frankston"],
    "Box Hill": ["Belgrave", "Lilydale"],
    "Brighton Beach": ["Sandringham"],
    "Broadmeadows": ["Craigieburn"],
    "Brunswick": ["Upfield"],
    "Burnley": ["Alamein", "Belgrave", "Glen Waverley", "Lilydale"],
    "Camberwell": ["Alamein", "Belgrave", "Lilydale"],
    "Carnegie": ["Pakenham", "Cranbourne"],
    "Chelsea": ["Frankston"],
    "Cheltenham": ["Frankston"],
    "Clayton": ["Pakenham", "Cranbourne"],
    "Clifton Hill": ["Mernda", "Hurstbridge"],
    "Coburg": ["Upfield"],
    "Cranbourne": ["Cranbourne"],
    "Crib Point": ["Stony Point"],
    "Dandenong": ["Pakenham", "Cranbourne"],
    "Dennis": ["Hurstbridge"],
    "Diamond Creek": ["Hurstbridge"],
    "Eaglemont": ["Hurstbridge"],
    "East Malvern": ["Glen Waverley"],
    "East Richmond": ["Alamein", "Belgrave", "Glen Waverley", "Lilydale"],
    "Elsternwick": ["Sandringham"],
    "Eltham": ["Hurstbridge"],
    "Essendon": ["Craigieburn"],
    "Fairfield": ["Hurstbridge"],
    "Flemington Bridge": ["Upfield"],
    "Flemington Racecourse": ["Flemington Racecourse"],
    "Flinders Street": ["All Lines"],
    "Footscray": ["Sunbury", "Werribee", "Williamstown"],
    "Gardenvale": ["Sandringham"],
    "Glen Waverley": ["Glen Waverley"],
    "Glenferrie": ["Alamein", "Belgrave", "Lilydale"],
    "Glenhuntly": ["Frankston"],
    "Gowrie": ["Upfield"],
    "Greensborough": ["Hurstbridge"],
    "Hampton": ["Sandringham"],
    "Hartwell": ["Alamein"],
    "Hawksburn": ["Frankston", "Pakenham", "Cranbourne"],
    "Hawthorn": ["Alamein", "Belgrave", "Lilydale"],
    "Heatherdale": ["Belgrave", "Lilydale"],
    "Heidelberg": ["Hurstbridge"],
    "Highett": ["Frankston"],
    "Hoppers Crossing": ["Werribee"],
    "Hurstbridge": ["Hurstbridge"],
    "Ivanhoe": ["Hurstbridge"],
    "Jacana": ["Craigieburn"],
    "Jewell": ["Upfield"],
    "Jolimont": ["Hurstbridge", "Mernda"],
    "Jordanville": ["Glen Waverley"],
    "Kensington": ["Craigieburn"],
    "Kooyong": ["Glen Waverley"],
    "Lalor": ["Mernda"],
    "Laverton": ["Werribee"],
    "Lilydale": ["Lilydale"],
    "Macaulay": ["Upfield"],
    "Macleod": ["Hurstbridge"],
    "Malvern": ["Frankston", "Pakenham", "Cranbourne"],
    "McKinnon": ["Frankston"],
    "Melbourne Central": ["All City Loop"],
    "Mentone": ["Frankston"],
    "Merlynston": ["Upfield"],
    "Mernda": ["Mernda"],
    "Middle Brighton": ["Sandringham"],
    "Middle Footscray": ["Sunbury"],
    "Mitcham": ["Belgrave", "Lilydale"],
    "Mont Albert": ["Belgrave", "Lilydale"],
    "Montmorency": ["Hurstbridge"],
    "Moonee Ponds": ["Craigieburn"],
    "Moorabbin": ["Frankston"],
    "Mordialloc": ["Frankston"],
    "Moreland": ["Upfield"],
    "Mount Waverley": ["Glen Waverley"],
    "Murrumbeena": ["Pakenham", "Cranbourne"],
    "Newport": ["Werribee", "Williamstown"],
    "North Brighton": ["Sandringham"],
    "North Melbourne": ["Craigieburn", "Sunbury", "Upfield", "Werribee", "Williamstown"],
    "North Richmond": ["Mernda", "Hurstbridge"],
    "Nunawading": ["Belgrave", "Lilydale"],
    "Oak Park": ["Craigieburn"],
    "Oakleigh": ["Pakenham", "Cranbourne"],
    "Parliament": ["All City Loop"],
    "Pascoe Vale": ["Craigieburn"],
    "Patterson": ["Frankston"],
    "Prahran": ["Frankston", "Pakenham", "Cranbourne"],
    "Preston": ["Mernda"],
    "Regent": ["Mernda"],
    "Reservoir": ["Mernda"],
    "Richmond": ["All Lines"],
    "Ringwood": ["Belgrave", "Lilydale"],
    "Rosanna": ["Hurstbridge"],
    "Roxburgh Park": ["Craigieburn"],
    "Royal Park": ["Upfield"],
    "Rushall": ["Mernda"],
    "Ruthven": ["Mernda"],
    "Sandringham": ["Sandringham"],
    "Seaford": ["Frankston"],
    "South Kensington": ["Werribee", "Williamstown"],
    "South Yarra": ["Frankston", "Pakenham", "Cranbourne", "Sandringham"],
    "Southern Cross": ["All Lines"],
    "Spotswood": ["Werribee", "Williamstown"],
    "St Albans": ["Sunbury"],
    "Strathmore": ["Craigieburn"],
    "Surrey Hills": ["Belgrave", "Lilydale"],
    "Syndal": ["Glen Waverley"],
    "Tecoma": ["Belgrave"],
    "Thornbury": ["Mernda"],
    "Toorak": ["Glen Waverley"],
    "Tooronga": ["Glen Waverley"],
    "Tottenham": ["Sunbury"],
    "Upper Ferntree Gully": ["Belgrave"],
    "Upfield": ["Upfield"],
    "Victoria Park": ["Mernda", "Hurstbridge"],
    "Watergardens": ["Sunbury"],
    "Watsonia": ["Hurstbridge"],
    "Wattle Glen": ["Hurstbridge"],
    "Werribee": ["Werribee"],
    "West Footscray": ["Sunbury"],
    "West Richmond": ["Mernda", "Hurstbridge"],
    "Westall": ["Pakenham", "Cranbourne"],
    "Westgarth": ["Mernda", "Hurstbridge"],
    "Williams Landing": ["Werribee"],
    "Williamstown": ["Williamstown"],
    "Williamstown Beach": ["Williamstown"],
    "Willison": ["Alamein"]
};