station_codes = {
    # Ivanhoe Was the Most recent station (following vicsig and sorting by name)
    
    # Clifton Hill Station Codes
    "CWD":  "Collingwood",
    "CHL":  "Clifton Hill",
    "CXT":  "Croxton",
    "BEL":  "Bell",
    "EPP":  "Epping",
    "HWS":  "Hawkstowe",
    "DEN":  "Dennis",
    "FFD":  "Fairfield",
    "ALP":	"Alphington",
    "DBN":  "Darebin",
    "IVA":  "Ivanhoe",
    "EGT":  "Eaglemont",
    "HDB":  "Heidelberg",
    "GRN":  "Greensborough",
    "ELT":  "Eltham",
    "DCK":  "Diamond Creek",
    "HBE":  "Hurstbridge",
    # Burnley Station Codes
    "ERM":  "East Richmond",
    "BLY":  "Burnley",
    "HAW":  "Hawthorn",
    "GFE":  "Glenferrie",
    "AUB":	"Auburn",
    "CAM":  "Camberwell",
    "ECM":  "East Camberwell",
    "CBY":  "Canterbury",
    "CHM":  "Chatham",
    "UNN":	"Union",
    "BOX":  "Box Hill",
    "BBN":  "Blackburn",
    "HTD":  "Heatherdale",
    "CDN":  "Croydon",
    "HMT":  "Heathmont",
    "BAY":  "Bayswater",
    "BOR":	"Boronia",
    "FTG":	"Ferntree Gully",
    "BEG":  "Belgrave",
    "HWL":  "Hartwell",
    "BWD":  "Burwood",
    "ASH":	"Ashburton",
    "ALM":  "Alamein",
    "HEY":  "Heyington",
    "GAR":  "Gardiner",
    "GIR":  "Glen Iris",
    "DLG":  "Darling",
    "EMV":  "East Malvern",
    "HOL":  "Holmesglen",
    "GWY":  "Glen Waverley",
    # Cran/Pak Station Codes
    "CFD":  "Caulfield",
    "CNE":  "Carnegie",
    "HUG":  "Hughesdale",
    "HUN":  "Huntingdale",
    "CLA":  "Clayton",
    "DNG":  "Dandenong",
    "HLM":  "Hallam",
    "BEW":  "Berwick",
    "BFD":  "Beaconsfield",
    "CDA":  "Cardinia Road",
    "EPH":	"East Pakenham",
    "CBE":  "Cranbourne",
    # Frankston/Stony Point Station Codes
    "HKN":  "Hawksburn",
    "ARM":	"Armadale",
    "GHY":  "Glen Huntly",
    "BEN":  "Bentleigh",
    "HIG":  "Highett",
    "CTM":  "Cheltenham",
    "CHE":  "Cheltenham", # Not Official but I know other use this
    "ASP":	"Aspendale",
    "EDI":  "Edithvale",
    "CSA":  "Chelsea",
    "BON":  "Bonbeach",
    "CAR":  "Carrum",
    "FKN":  "Frankston",
    "BXR":  "Baxter",
    "HST":  "Hastings",
    "BIT":  "Bittern",
    "CPT":  "Crib Point",
    # Sandringham Station Codes
    "BCV":  "Balaclava",
    "ELS":  "Elsternwick",
    "GVE":  "Gardenvale",
    "BBH":  "Brighton Beach",
    "HAM":  "Hampton",
    # Werribee/Williamstown Station Codes
    "ALT":	"Altona",
    "ACF":	"Aircraft",
    "HCG":  "Hoppers Crossing",

    # Sunbury Station Codes
    "ALB":	"Albion",
    "GIN":  "Ginifer",
    "DIT":  "Diggers Rest",

    # Flemington Racecourse Station Codes
    "RCE":  "Flemington Racecourse",
    
    # Craigieburn Station Codes
    "ASV":	"Ascot Vale",
    "ESD":  "Essendon",
    "GBV":  "Glenbervie",
    "GRY":  "Glenroy",
    "BMS":  "Broadmeadows",
    "CLO":  "Coolaroo",
    "CGB":  "Craigieburn",
    # Upfield Station Codes
    "FBD":  "Flemington Bridge",
    "BWK":  "Brunswick",
    "ASY":	"Anstey",
    "COB":  "Coburg",
    "BAT":  "Batman",
    "FAK":  "Fawkner",
    "GOW":  "Gowrie",
    # Misc/VLine Station Codes
    "ALY":	"Albury",
    "ART":	"Ararat",
    "ADR":	"Ardeer",
    "BMH":  "Bacchus Marsh",
    "BRD":  "Bairnsdale",
    "TNT":	"Tarneit",
    "WPD":	"Waurn Ponds",
    "WVL":	"Wyndham Vale",
    "CPS":	"Caroline Springs",
    "TLN":	"Cobblebank",
    "BNV":  "Ballan",
    "BAL":  "Ballarat",
    "BNL":  "Benalla", # still open but apparently wont have any departures for a bit
    "BDG":  "Bendigo",
    "BRF":  "Broadford",
    "BYP":  "Bunyip",
    "CPD":  "Camperdown",
    "CME":  "Castlemaine",
    "CLV":  "Clunes",
    "COL":  "Colac",
    "CDH":  "Condah",
    "CWK":  "Creswick",
    "DPK":  "Deer Park",
    "DGE":  "Dingee",
    "DBK":  "Donnybrook",
    "DRO":  "Drouin",
    "EAG":  "Eaglehawk",
    "ECH":  "Echuca",
    "GFD":  "Garfield",
    "GLG":  "Geelong",
    "GIS":  "Gisborne",
    "HEV":  "Healesville",
    "HCJ":  "Heathcote Junction",
    
    # Inner City stations With too many lines
    "FSS":	"Flinders Street",
    "SSS":	"Southern Cross",
    "SCS":	"Southern Cross", # Not official that may be used by one or 2 people
    "FGS":	"Flagstaff",
    "MCE":	"Melbourne Central",
    "PAR":	"Parliament",
    "ARN":	"Arden",
    "PKV":	"Parkville",
    "STL":	"State Library",
    "THL":	"Town Hall",
    "AZC":	"Anzac",
    "NME":	"North Melbourne",
    "RMD":	"Richmond",
    "FSY":  "Footscray",
    
    # Added early for specific people
    "SYN":	"Syndal",

    # Three Letter Stations
    "MOE":	"Moe",
    
    
    
}
